# .github/workflows/build-tf-plan.yml

name: 'BUILD - Terraform Plan'

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'modules/**/*.tf'
  push:
    branches:
      - main
    paths:
      - 'modules/**/*.tf'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
        continue-on-error: true

      - name: Get added and modified files
        run: |
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "File Added/Modified : ${added_modified_file}" 
          done
          DIR="$(dirname ${added_modified_files[0]})"
          echo "ENV_DIR=${DIR}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Get removed files
        run: |
          readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
          for removed_file in ${removed_files[@]}; do
            echo "File Removed : ${removed_file}" 
          done
          DIR="$(dirname ${removed_files[0]})"
          echo "ENV_DIR=${DIR}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.15.0

      - name: Set environment
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/.github/workflows/fake-key.json" >> $GITHUB_ENV
          echo $GOOGLE_APPLICATION_CREDENTIALS # This will print the file path in GOOGLE_APPLICATION_CREDENTIALS variable
          # cat $GOOGLE_APPLICATION_CREDENTIALS # This will print the file content

      - name: Terraform Format
        working-directory: ${{ env.ENV_DIR }}
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      # - name: Post Format
      #   if: always() && github.ref != 'refs/heads/master' && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure')
      #   uses: robburger/terraform-pr-commenter@v1
      #   with:
      #     commenter_type: fmt
      #     commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}

      - name: Terraform Init
        working-directory: ${{ env.ENV_DIR }}
        id: init
        run: terraform init

      # - name: Post Init
      #   if: always() && github.ref != 'refs/heads/master' && (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
      #   uses: robburger/terraform-pr-commenter@v1
      #   with:
      #     commenter_type: init
      #     commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.init.outputs.exitcode }}

      - name: Terraform Validate
        working-directory: ${{ env.ENV_DIR }}
        id: validate
        run: terraform validate

      # - name: Post Validate
      #   if: always() && github.ref != 'refs/heads/master' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure')
      #   uses: robburger/terraform-pr-commenter@v1
      #   with:
      #     commenter_type: validate
      #     commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

      - name: Terraform Plan
        working-directory: ${{ env.ENV_DIR }}
        id: plan
        run: terraform plan -out workspace.plan
        env:
          TF_VAR_billing_account: 'ABCD-EFGH-IJKL-MNOP'
          TF_VAR_parent: 'organizations/1234567890'

      # - name: Post Plan
      #   if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      #   uses: robburger/terraform-pr-commenter@v1
      #   with:
      #     commenter_type: plan
      #     commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.plan.outputs.exitcode }}