name: RLUI
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radlab-ui/webapp
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: ./radlab-ui/webapp/package-lock.json 
    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2
      with:
        path: radlab-ui/webapp
        mode: production
    - name: "Install Node dependencies"
      run: npm ci
    - name: Test Cases
      run: npm test
  build:
    name: NextJS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radlab-ui/webapp
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: ./radlab-ui/webapp/package-lock.json
    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2
      with:
        path: radlab-ui/webapp
        mode: production
    - name: Install Node dependencies
      run: npm ci
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: "my-api-key"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "my-auth-domain"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "my-project-id"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "my-storage-bucket"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "my-messaging-sender-id"
        NEXT_PUBLIC_FIREBASE_APP_ID: "my-firebase-app-id"
        NEXT_PUBLIC_RAD_LAB_DOCS_SITE: "https://googlecloudplatform.github.io/rad-lab/"

